python: can't open file '/home/neuronet_team095/coli-project/sic_cluster/main.py': [Errno 2] No such file or directory

ERROR conda.cli.main_run:execute(124): `conda run bash /home/neuronet_team095/coli-project/sic_cluster/run.sh` failed. (See above for error)
